import 'package:ebook_app/models/BookModel.dart';

var categoryData = [
  {"Icon": "Assets/Icons/heart.svg", "label": " Programming Languages"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Data Structures"},
  {"Icon": "Assets/Icons/heart.svg", "label": "DBMS"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Operating Systems"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Computer Networks"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Software Engineering"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Web Technologies"},
  {"Icon": "Assets/Icons/heart.svg", "label": "OOP"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Computer Architecture"},
  {
    "Icon": "Assets/Icons/heart.svg",
    "label": "Mathematics for Computer Science"
  },
  {"Icon": "Assets/Icons/heart.svg", "label": "Cybersecurity"},
  {"Icon": "Assets/Icons/heart.svg", "label": "Mobile Application Development"},
  {"Icon": "Assets/Icons/heart.svg", "label": "AI"},
  {
    "Icon": "Assets/Icons/heart.svg",
    "label": "Ethical Hacking and Cyber Forensics "
  },
  {"Icon": "Assets/Icons/heart.svg", "label": "Project Work"},
];

var bookData = [
  BookModel(
      id: "1",
      title: "C",
      description:
          "The C programming language was invented in the early 1970s, and since then has become one of the most popular and widely used generalpurpose languages. It’s used by a wide range of programmers, from amateurs working on simple projects at home, to industry professionals who write in C for a living. This series is an introduction to programming in C for absolute beginners; Simon Long",
      aboutAuthor:
          "Simon Long is a software engineer at Raspberry Pi, with a particular interest in user interface design. He first started writing C in the early 90s, and since then he’s written software for a wide variety of electronic products, from mobile phones to medical equipment.",
      author: "Simon Long",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: " Programming Languages",
      bookurl:
          "file:///C:/Users/RAJESH/OneDrive/Desktop/app/ebook_app/Assets/category/Computer%20and%20Programming%20Languages/c/Essentials_C_v1.pdf"),
  BookModel(
      id: "2",
      title: "Python",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: " Programming Languages"),
  BookModel(
      id: "3",
      title: "Python",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: " Programming Languages"),
  BookModel(
      id: "4",
      title: "C-Sharp",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: " Programming Languages"),
  BookModel(
      id: "5",
      title: "C-Sharp",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: "Programming Languages"),
  BookModel(
      id: "6",
      title: "C-Sharp",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      category: " Programming Languages"),
  BookModel(
      id: "7",
      title: "C-Sharp",
      description: "",
      aboutAuthor: "",
      author: "ketan",
      coverUrl: "Assets/Images/Python.jpg",
      pages: 93,
      language: "ENG",
      rating: "4.5",
      numberofRating: 10,
      category: " Programming Languages"),
];
