// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdhYwQOGSsdPuVLPZROeBxpAA0IrKqxQ',
    appId: '1:225320424878:web:9ea2774d809fa83c72643f',
    messagingSenderId: '225320424878',
    projectId: 'ebook-app-32ba8',
    authDomain: 'ebook-app-32ba8.firebaseapp.com',
    storageBucket: 'ebook-app-32ba8.appspot.com',
    measurementId: 'G-30JRP3WLGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo7fAIShHzZVPtoDsUdkTt3r6HKFVwXME',
    appId: '1:225320424878:android:aaf5d96969aeaeaf72643f',
    messagingSenderId: '225320424878',
    projectId: 'ebook-app-32ba8',
    storageBucket: 'ebook-app-32ba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhMFIVn-nmLyOqcGafNpHvshHrrzqvaM',
    appId: '1:225320424878:ios:28bc0b939a1176c972643f',
    messagingSenderId: '225320424878',
    projectId: 'ebook-app-32ba8',
    storageBucket: 'ebook-app-32ba8.appspot.com',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhMFIVn-nmLyOqcGafNpHvshHrrzqvaM',
    appId: '1:225320424878:ios:fb64c478c0d85af672643f',
    messagingSenderId: '225320424878',
    projectId: 'ebook-app-32ba8',
    storageBucket: 'ebook-app-32ba8.appspot.com',
    iosBundleId: 'com.example.ebookApp.RunnerTests',
  );
}
